# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
  Khas untuk pelajar-pelajar pengajian Master dan PhD di UPSI (Universiti Pendidikan Sultan Idris). 
  Kini anda tidak perlu bersusah payah dan membuang masa membetulkan format tesis/disertasi. 
  Format IPS adalah acuan tesis/disertasi yang akan membantu anda!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Abd Halim
email: halimstt@gmail.com
facebook_username:
twitter_username:
github:
  username: BroSpek
  project: format-ips
#address:
#  - line: 22 Jalan U1/1
#  - line: Taman Universiti
#  - line: 35900 Tanjong Malim

telephone: 011-1544 2546
copyright: Format IPS

# API settings
google_api_key:

# Build settings
markdown: kramdown