# Site settings
title: Format IPS
email: halimstt@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Khas untuk pelajar-pelajar pengajian Master dan PhD di UPSI (Universiti Pendidikan Sultan Idris). 
  Kini anda tidak perlu bersusah payah dan membuang masa membetulkan format tesis/disertasi. 
  Format IPS adalah acuan tesis/disertasi yang akan membantu anda!
url: "" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/

# User setting
owner: Abd Halim
author: Abd Halim
email: halimstt@gmail.com
facebook_username:
twitter_username:
github:
  username: BroSpek
  project: format-ips
telephone: 011-1544 2546

# Build settings
markdown: kramdown

# exclude files
exclude: ['less','LICENSE','README.md','gulpfile.js','package.json']